services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: usermanagement_db
      POSTGRES_USER: usermanagement_user
      POSTGRES_PASSWORD: usermanagement_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DB_SERVER_URL: jdbc:postgresql://postgres:5432/usermanagement_db
      DB_USER: usermanagement_user
      DB_PASSWORD: usermanagement_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data:
